### ISSUE TITLE
Feature request: Ability to color circles at node tipes one color or remove them entirely

### ISSUE THREAD

**Issue by slvrshot** [emvolz-phylodynamics/treestructure#8]
I am following your phylodynamics tutorial and understand why the colored circles are there but they can be a bit distracting especially when looking at the colors of the various partitions. There are too often too many colors.

**Comment by emvolz** [comment]
We could add options to suppress tip & line colours. 
Note that if using ggtree, the plot command will return a ggtree object that can be customized further. 
You can identify the layers that you want to suppress in `$layers` and then overwrite them. Here is an example that removes the node points : 
```
p <- plot( treestructurefit )
pp <- p 
pp$layers[[3]] <- ggtree::geom_nodepoint( size = 0 )
```
If you want to try generating these tree plots from scratch, the code is not very long: 
https://github.com/emvolz-phylodynamics/treestructure/blob/d303d7fe4ea34de9c8de0b7cf5a4b79fc324d637/R/m13.R#L474
The plots could be customized in many ways

**Comment by slvrshot** [comment]
That did work! This is great. However I did notice an additional issue when working with treestructure. It appears when you add a gheatmap that the line for the colors are not plotted equidistantly. This causes the tree colors to alternate between solid to washed out. I don't have this issue when working with a normal tree object using the ggtree object. Is there anyway to correct this behavior. I have added my code and images for reference: 

```
library( treestructure )
# change the class to ape::phylo 
phylo.s.dtr1 <- td
td
class( phylo.s.dtr1 ) <- 'phylo' 
# note this is a ladder-like tree, so will require some time-overlap between partitions
( ts0 <- trestruct(phylo.s.dtr1, minCladeSize = 25, minOverlap = 24, nsim = 1e4, level = .05, ncpu = 32 ) )
ts0

pp <- p
pp$layers[[3]] <- ggtree::geom_nodepoint( size = 0) 
p2 <- gheatmap(pp, test, offset=.01, width=1, colnames=TRUE, font.size =3, colnames_position = "top",colnames_angle = 45, colnames_offset_y=10, hjust=0) +
  scale_fill_manual(values=cols, breaks = c("North America","Asia,"South America","Unknown",
          "Europe","Oceania","Susceptible","Elevated", "Other",
        "TRUE","WT","Mutation") + scale_x_continuous(breaks=c(1880,1890,1900,1910,1920,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020))
p2
```
Is it a line spacing issue? Thanks!

![Annotation 2020-02-07 135654](https://user-images.githubusercontent.com/16061438/74057416-e1874880-49b1-11ea-960b-d0f20537b62f.png)

![image](https://user-images.githubusercontent.com/16061438/74057926-e698c780-49b2-11ea-9843-5535a09695f7.png)

**Comment by slvrshot** [comment]
Closing. Set Color = FALSE in gheatmap to remove white lines.
